# Spring Boot2.x中，默认只开放了info、health两个端点，
# 剩余的需要自己通过配置management.endpoints.web.exposure.include属性来加载
management:
  endpoints:
    health:
      show-details: always # 把health细节展示出来
    web:
      exposure:
        include: '*' # 你要暴露哪些端点
#        exclude:     # 不暴露哪些端点
    shutdown:
      # 如果想单独操作某个端点可以使用management.endpoint.端点.enabled属性进行启用或禁用
      enable: false # 禁用shutdown这个端点
  server:
    servlet:
      # http://localhost:8081/management/actuator/beans
      context-path: /management # 自定义端点的路径,这样就可以结合spring-scurity进行权限控制了.
    port: 8081

# 配置info端点的信息,然后访问: http://localhost:8080/actuator/info
info:
  blog-url: myblog.url
  author: xzj
  version: @project.version@

# 路径映射，将 health 路径映射成 rest_health 那么在访问 health 路径将为404，
# 因为原路径已经变成 rest_health 了，一般情况下不建议使用
# management.endpoints.web.path-mapping.health=rest_health