spring:
  elasticsearch:
    jest:
      uris: http://192.168.32.134:9200, http://192.168.32.134:9201, http://192.168.32.134:9203
      #username: elastic
      #password: 123456
      read-timeout: 20000 #读取超时
      connection-timeout: 20000 #连接超时

server:
  port: 9090
