server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.32.150:3307/learn
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
  druid:
    initialSize: 2
    minIdle: 2
    maxActive: 2
  rabbitmq:
    host: 192.168.32.150
    port: 5672
    username: guest
    password: guest
    virtual-host: / # 虚拟主机